import { Raleway } from 'next/font/google'
import './globals.css'
import Nav from './components/Nav'
import Footer from './components/sections/Footer'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  )
}
